---
abstract: 'Test JavaScript with Jasmine BDD framework from Perl'
author:
  - 'Alexander Tokarev <tokarev@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WWW-Jasmine
no_index:
  directory:
    - t
    - inc
requires:
  WWW::Selenium: 1.33
resources:
  bugtracker: http://github.com/nohuhu/Test-WWW-Jasmine/issues
  repository: http://github.com/nohuhu/Test-WWW-Jasmine
version: 0.01
